### PR TITLE
Challenge fails with Connection refused (challenge type http-01)

### PR DESCRIPTION
**Pull request by YetaWF**
https://github.com/ffMathy/FluffySpoon.AspNet.LetsEncrypt/issues/36

Adds a new StartUpMode option to define when cert requests/renewals are initiated.
StartupMode.Immediate (default) is identical to the current implementation.
StartUpMode.Manual requires an explicit call to app.RunFluffySpoonLetsEncrypt (at the end of Startup.Configure) to request/renew certs.
StartUpMode.Delayed defers until app.UseFluffySpoonLetsEncrypt is called.

### CODE REVIEW

**Comment by ffMathy** [comment]
Instead of this, can we use a IApplicationLifetime to hook into when the application has started, and only start the timer at that time?

https://stackoverflow.com/q/57799344/553609

**Comment by YetaWF** [comment]
That's actually much better. Still using options? Or should this be the default? I didn't really like the options (StartUpMode), just wanted to get it working without disrupting anything.

**Comment by ffMathy** [comment]
I'd prefer not to have the options as you mention yourself - the FluffySpoon packages are designed to be as simple to use as possible for solving very specific responsibilities, with minimal configuration options.

Sorry that you worked on this for nothing 😢

**Comment by YetaWF** [comment]
I have updated the PR after your last comment to keep it with the minimal config approach. If the PR isn't appropriate, you can close it as I'm using a patched local version now anyway.

**Pull request merged**
