### PR TITLE
Challenge response null guard

### PR DESCRIPTION
**Pull request by killswtch**
Possible fix for #18, or at least a workaround, with a log warning for when instances of null challenge responses occur.

### CODE REVIEW

**Comment by ffMathy** [comment]
You're the best! ♥️

**Comment by zigszigsdk** [comment]
Which release does/will this correspond to? I seem to have the same issue out of nowhere. What's bizzar is that when I roll back, it still doesn't seem to be working.

**Comment by ffMathy** [comment]
Thanks for chiming in @zigszigsdk. This should be in 1.128.0.

That's very strange indeed. Could use a helping hand with this, towards your environment!

**Comment by zigszigsdk** [comment]
I'm still investigating. I just made an edit to the post above. 

Furthermore, I just found that if I try to remove the FluffySpoonAspNetLetsEncryptCertificate_* files from the version that did work, it runs into an error as well, seeminly during, or after the acmechallenge.

I'll edit when I have the details - or would you rather have a new thread?

**Comment by ffMathy** [comment]
Interesting thought. Perhaps we should update the dependencies of this library.

**Comment by zigszigsdk** [comment]
I finally had time to look at this issue again today, and put the time in to learn VS <-> linux offroad debugging.

The lack of a proper error message is because LetsEncryptRenewalService.cs:275 chokes on the Challenges, which both have a null in the Error property.

I fixed this by putting a "null"-string in place of the null values if null, https://github.com/zigszigsdk/FluffySpoon.AspNet.LetsEncrypt

However now it seems that the code gets stuck in an infinite loop at LetsEncryptRenewalService.cs:294 because the second challenge (Type: "dns-01") never switches away from "Pending".
I'll have to investigate further to figure out why exactly that is.

**Comment by ffMathy** [comment]
Keep up the good detective work! :+1:

**Comment by zigszigsdk** [comment]
The issue was indeed that it tried to wait for all challenges to resolve. Since the DNS challenge has something like 5 days to resolve, it sits in "pending" mode all the time.

This confirms that something has changed, but I'm still not sure what. It could either be that the time to resolve the DNS challenge has been increased, or that it's even included in the first place.

Either way, changing the check to either look for one valid, or all invalid fixes it for me. I've made a pull request https://github.com/ffMathy/FluffySpoon.AspNet.LetsEncrypt/pull/21

**Pull request merged**
