### PR TITLE
Fix challenge deletions

### PR DESCRIPTION
**Pull request by killswtch**
Fixed a null reference caused by residual code from before the introduction of challenge deletion. Also improved how deletions are handled by various challenge persistence strategies, and improved the readability of DistributedCacheChallengePersistenceStrategy.

### CODE REVIEW

**Comment by killswtch** [comment]
Unfortunately our Azure account has gotten into a bit of a bizarre state that has left us and Microsoft stumped. We don't seem to be able to 'see' stored certificates, and they won't bind. Thus I can no longer fully test the Azure strategies. It looks like we might have to use the new free certificates in Azure instead of this library :(

**Comment by ffMathy** [comment]
That's unfortunate, but I'm happy you found a more "official" way of finding certificates.

Is there a way to remedy it?

**Comment by killswtch** [comment]
I hope to look into it at some point. Our problems with Azure (unable to create web apps) have set us back a couple of weeks, so I don't have the time now unfortunately. At the moment there's no way to automate the generation of certificates in Azure, so Lets Encrypt has one up on Microsoft for the time being. I've had to manually create and bind the certificates.

**Comment by ffMathy** [comment]
Wow, that really sucks. I wish you the best in the future - I hope you find a way.

**Pull request merged**
